### ISSUE TITLE
Laminas support

### ISSUE THREAD

**Issue by andrea-trivisonno** [boesing/zend-cache-redis-cluster#1]
Do you plan support for Laminas framework?

**Comment by boesing** [comment]
Hey @andrea-trivisonno,

yes. I am actually moving this package to laminas. However, you have to change the package name in your `composer.json` aswell as I dont plan to migrate this package but create a new one.
It depends on `laminas-cache` v2.10 (which is not yet released, but there is an RC version for over a week now. I plan to release it this weekend).

The new package will be [boesing/laminas-cache-storage-adapter-redis-cluster](https://github.com/boesing/laminas-cache-storage-adapter-redis-cluster/).
